:sparkles: new ci

diff --git a/.github/workflows/Release.yml b/.github/workflows/Release.yml
--- a/.github/workflows/Release.yml
+++ b/.github/workflows/Release.yml
@@ -7,6 +7,9 @@ env:
   GH_TOKEN: ${{ secrets.GH_TOKEN }}
   RUST_TOOLCHAIN: nightly-2025-02-26
   NDK_VERSION: 25.2.9519653
+  FLUTTER_CHANNEL: stable
+  FLUTTER_VERSION: '3.7.3'
+  JDK_VERSION: 17
 
 jobs:
 
@@ -16,39 +19,64 @@ jobs:
     needs:
       - check_release
       - build_release_assets
-      - community_notify
     steps:
       - run: exit 0
 
   check_release:
     name: Check release
     runs-on: ubuntu-latest
+    outputs:
+      matrix: ${{ steps.check-release.outputs.matrix }}
     steps:
-      - name: Cargo cache
-        uses: actions/cache@v3
-        with:
-          path: |
-            ~/.cargo/bin/
-            ~/.cargo/registry/index/
-            ~/.cargo/registry/cache/
-            ~/.cargo/git/db/
-          key: ${{ runner .os }}-cargo-
-
-      - name: Install rust toolchain
-        uses: actions-rs/toolchain@v1
-        with:
-          toolchain: ${{ env.RUST_TOOLCHAIN }}
-
       - name: Checkout
         uses: actions/checkout@v3
-        with:
-          repository: ${{ github.event.inputs.repo }}
-          ref: 'master'
 
-      - name: Check release
+      - name: Check and create release
+        id: check-release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
         run: |
-          cd ci
-          cargo run --bin check-release
+          export VERSION=$(cat ci/version.code.txt | xargs echo)
+          echo "VERSION : $VERSION"
+          declare -A asset_dict
+          asset_dict["ios"]="${{ github.event.repository.name }}-$VERSION-nosign.ipa"
+          asset_dict["android-arm64"]="${{ github.event.repository.name }}-arm64-$VERSION.apk"
+          asset_dict["windows"]="${{ github.event.repository.name }}-$VERSION-windows-x86_64.zip"
+          asset_dict["linux"]="${{ github.event.repository.name }}-$VERSION.AppImage"
+          asset_dict["macos"]="${{ github.event.repository.name }}-$VERSION.dmg"
+          declare -A host_dict
+          host_dict["ios"]="macos-latest"
+          host_dict["android-arm64"]="ubuntu-latest"
+          host_dict["windows"]="windows-latest"
+          host_dict["linux"]="ubuntu-latest"
+          host_dict["macos"]="macos-latest"
+          export RELEASE=$(gh release view $VERSION --json id -q .id || echo "NOT_FOUND")
+          echo "RELEASE : $RELEASE"
+          if [ "$RELEASE" == "NOT_FOUND" ]; then
+            echo "Release does not exist. Creating release $VERSION."
+            gh release create $VERSION -F ci/version.info.txt --target ${{ github.sha }}
+          else
+            echo "Release $VERSION already exists."
+          fi
+          gh release view $VERSION --json assets > release_assets.json
+          echo release_assets.json :
+          cat release_assets.json
+          matrix='['
+          for key in "${!asset_dict[@]}"; do
+            asset_name=${asset_dict[$key]}
+            asset_exists=$(jq ".assets[].label" release_assets.json | grep -Fx "\"$asset_name\"" || echo "NOT_FOUND")
+            if [ "$asset_exists" == "NOT_FOUND" ]; then
+              echo "Asset $asset_name does not exist. Upload is required."
+              matrix+="{\"target\": \"$key\", \"host\": \"${host_dict[$key]}\"},"
+            else
+              echo "Asset $asset_name already exists. No upload is required."
+            fi
+          done
+          matrix=${matrix%,} # Remove trailing comma
+          matrix+=']'
+          echo matrix=$matrix >> $GITHUB_OUTPUT
+          echo "GITHUB_OUTPUT : $GITHUB_OUTPUT :"
+          cat $GITHUB_OUTPUT
 
   build_release_assets:
     name: Build release assets
@@ -57,46 +85,9 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        config:
-          - target: linux
-            host: ubuntu-latest
-            flutter_version: '3.7.3'
-            flutter_channel: 'stable'
-          - target: windows
-            host: windows-latest
-            flutter_version: '3.7.3'
-            flutter_channel: 'stable'
-          - target: macos
-            host: macos-latest
-            flutter_version: '3.7.3'
-            flutter_channel: 'stable'
-          - target: ios
-            host: macos-latest
-            flutter_version: '3.7.3'
-            flutter_channel: 'stable'
-          - target: android-arm32
-            host: ubuntu-latest
-            flutter_version: '3.7.3'
-            flutter_channel: 'stable'
-          - target: android-arm64
-            host: ubuntu-latest
-            flutter_version: '3.7.3'
-            flutter_channel: 'stable'
-          - target: android-x86_64
-            host: ubuntu-latest
-            flutter_version: '3.7.3'
-            flutter_channel: 'stable'
-          # - target: ohos-arm64
-          #   host: macos-latest
-          #   flutter_version: '3.7.3'
-          #   flutter_channel: 'stable'
+        config: ${{ fromJson(needs.check_release.outputs.matrix) }}
 
     runs-on: ${{ matrix.config.host }}
-
-    env:
-      TARGET: ${{ matrix.config.target }}
-      flutter_version: ${{ matrix.config.flutter_version }}
-      flutter_channel: ${{ matrix.config.flutter_channel }}
 
     steps:
       - name: Checkout
@@ -117,14 +108,7 @@ jobs:
         with:
           toolchain: ${{ env.RUST_TOOLCHAIN }}
 
-      - id: check_asset
-        name: Check asset
-        run: |
-          cd ci
-          cargo run --bin check-asset
-
       - name: checkout core
-        if: steps.check_asset.outputs.skip_build != 'true'
         uses: actions/checkout@v3
         with:
           token: ${{ secrets.GH_TOKEN }}
@@ -132,77 +116,61 @@ jobs:
           path: 'native'
 
       - name: Cache Flutter dependencies (Linux/Android)
-        if: steps.check_asset.outputs.skip_build != 'true' && matrix.config.host == 'ubuntu-latest'
+        if: matrix.config.host == 'ubuntu-latest'
         uses: actions/cache@v3
         with:
           path: /opt/hostedtoolcache/flutter
           key: ${{ runner.os }}-flutter
 
       - name: Setup flutter
-        if: steps.check_asset.outputs.skip_build != 'true'
         uses: subosito/flutter-action@v2
         with:
-          channel: ${{ env.flutter_channel }}
-          flutter-version: ${{ env.flutter_version }}
+          channel: ${{ env.FLUTTER_CHANNEL }}
+          flutter-version: ${{ env.FLUTTER_VERSION }}
           architecture: x64
 
-      - if: matrix.config.target == 'ohos-arm64' && steps.check_asset.outputs.skip_build != 'true'
-        name: Setup OpenHarmony SDK
-        shell: bash
-        run: |
-          rm -rf "/usr/local/share/boost"
-          rm -rf "$AGENT_TOOLSDIRECTORY"
-          cd $(dirname $(dirname $(realpath $(which flutter))))
-          git config --global --add safe.directory ${{ env.FLUTTER_ROOT }}
-          git remote ser-url origin https://gitcode.com/openharmony-sig/flutter_flutter.git'
-          git fetch
-          git checkout 3.22.0-ohos
-          git remote prune origin
-
       - name: Install cargo tools (non-android)
-        if: steps.check_asset.outputs.skip_build != 'true' && ( matrix.config.target == 'macos' || matrix.config.target == 'windows' || matrix.config.target == 'linux' || matrix.config.target == 'ios' )
+        if: ( matrix.config.target == 'macos' || matrix.config.target == 'windows' || matrix.config.target == 'linux' || matrix.config.target == 'ios' )
         run: |
           cargo install --force cbindgen
 
       - name: Install cargo tools (Android)
-        if: steps.check_asset.outputs.skip_build != 'true' && ( matrix.config.target == 'android-arm32' || matrix.config.target == 'android-arm64' || matrix.config.target == 'android-x86_64' )
+        if: ( matrix.config.target == 'android-arm32' || matrix.config.target == 'android-arm64' || matrix.config.target == 'android-x86_64' )
         run: |
           cargo install --force cargo-ndk
 
       - name: Setup java (Android)
-        if: steps.check_asset.outputs.skip_build != 'true' && ( matrix.config.target == 'android-arm32' || matrix.config.target == 'android-arm64' || matrix.config.target == 'android-x86_64' )
+        if: ( matrix.config.target == 'android-arm32' || matrix.config.target == 'android-arm64' || matrix.config.target == 'android-x86_64' )
         uses: actions/setup-java@v3
         with:
-          java-version: '17'
+          java-version: ${{ env.JDK_VERSION }}
           distribution: 'temurin'
 
       - name: Setup android tools (Android)
-        if: steps.check_asset.outputs.skip_build != 'true' && ( matrix.config.target == 'android-arm32' || matrix.config.target == 'android-arm64' || matrix.config.target == 'android-x86_64' )
+        if: ( matrix.config.target == 'android-arm32' || matrix.config.target == 'android-arm64' || matrix.config.target == 'android-x86_64' )
         uses: android-actions/setup-android@v3
         with:
           cmdline-tools-version: 8512546
           packages: 'platform-tools platforms;android-32 build-tools;30.0.2 ndk;${{ env.NDK_VERSION }}'
 
       - name: Install libfuse2 (Linux)
-        if: steps.check_asset.outputs.skip_build != 'true' && matrix.config.target == 'linux'
+        if: matrix.config.target == 'linux'
         run: |
           sudo apt update
           sudo apt install -y libfuse2
 
       - name: Set-Version (All)
-        if: steps.check_asset.outputs.skip_build != 'true'
         run: |
           cd ci
           cp version.code.txt ../lib/assets/version.txt
-          
 
       - name: Append application-identifier (ios)
-        if: steps.check_asset.outputs.skip_build != 'true' && ( matrix.config.target == 'ios')
+        if: ( matrix.config.target == 'ios')
         run: |
           /usr/libexec/PlistBuddy -c 'Add :application-identifier string opensource.jasmine' ios/Runner/Info.plist
 
       - name: Install rust target and build (ios)
-        if: steps.check_asset.outputs.skip_build != 'true' && ( matrix.config.target == 'ios')
+        if: ( matrix.config.target == 'ios')
         run: |
           rustup target install aarch64-apple-ios
           cargo build --manifest-path native/jmbackend/platforms/ios/Cargo.toml --features= --lib --release --target=aarch64-apple-ios
@@ -227,35 +195,8 @@ jobs:
       # lipo -create -output ios/librust.a native/jmbackend/platforms/ios-sim/target/x86_64-apple-ios/release/librust.a native/jmbackend/platforms/ios-sim/target/aarch64-apple-ios-sim/release/librust.a
       # cbindgen native/jmbackend/src/lib.rs -l c > ios/rust.h
 
-      # - if: matrix.config.target == 'ohos-arm64'
-      #   name: Setup OpenHarmony SDK
-      #   uses: openharmony-rs/setup-ohos-sdk@v0.2.1
-      #   id: setup-ohos
-      #   with:
-      #     version: "5.0.1"
-
-      - if: matrix.config.target == 'ohos-arm64'
-        name: Install rust target and build (ohos)
-        run: |
-          export PATH=/opt/harmonyos-tools/command-line-tools/ohpm/bin:$PATH
-          export PATH=/opt/harmonyos-tools/command-line-tools/bin:$PATH
-          export OHOS_NDK_HOME=/opt/harmonyos-tools/command-line-tools/sdk/default/openharmony
-          export OHOS_BASE_SDK_HOME=$OHOS_NDK_HOME
-          export OHOS_SDK_NATIVE=$OHOS_NDK_HOME
-          export HOS_SDK_HOME=$OHOS_NDK_HOME
-          export OHOS_SDK_HOME=$OHOS_NDK_HOME
-
-          rustup target add aarch64-unknown-linux-ohos
-          cargo install ohrs
-          bash scripts/ohos-native.sh
-          rm -rf native
-
-          sed -i 's/  modal_bottom_sheet: \^3.0.0-pre/  modal_bottom_sheet:\n    git:\n      url: https:\/\/github.com\/niuhuan\/modal_bottom_sheet.git\n      branch: ohos\n      path: modal_bottom_sheet/g' pubspec.yaml
-
-          flutter build hap --target-platform ohos-arm64
-
       - name: Install rust target and build (Android-arm64)
-        if: steps.check_asset.outputs.skip_build != 'true' && ( matrix.config.target == 'android-arm64')
+        if: ( matrix.config.target == 'android-arm64')
         run: |
           export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/${{ env.NDK_VERSION }}
           rustup target install aarch64-linux-android
@@ -265,7 +206,7 @@ jobs:
           flutter build apk --target-platform android-arm64
 
       - name: Install rust target and build (Android-arm32)
-        if: steps.check_asset.outputs.skip_build != 'true' && ( matrix.config.target == 'android-arm32')
+        if: ( matrix.config.target == 'android-arm32')
         run: |
           export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/${{ env.NDK_VERSION }}
           rustup target install armv7-linux-androideabi
@@ -275,7 +216,7 @@ jobs:
           flutter build apk --target-platform android-arm
 
       - name: Install rust target and build (Android-x86_64)
-        if: steps.check_asset.outputs.skip_build != 'true' && ( matrix.config.target == 'android-x86_64')
+        if: ( matrix.config.target == 'android-x86_64')
         run: |
           export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/${{ env.NDK_VERSION }}
           rustup target install x86_64-linux-android
@@ -285,7 +226,7 @@ jobs:
           flutter build apk --target-platform android-x64
 
       - name: Install dependencies and build (Linux)
-        if: steps.check_asset.outputs.skip_build != 'true' && matrix.config.target == 'linux'
+        if: matrix.config.target == 'linux'
         run: |
           sudo apt-get update
           sudo apt install -y ninja-build liblzma-dev libgtk-3-dev libgl1-mesa-dev xorg-dev
@@ -308,7 +249,7 @@ jobs:
 
 
       - name: build (windows)
-        if: steps.check_asset.outputs.skip_build != 'true' && matrix.config.target == 'windows'
+        if: matrix.config.target == 'windows'
         run: |
           cargo build --manifest-path native/jmbackend/platforms/windows/Cargo.toml --release --target x86_64-pc-windows-msvc
           cp native/jmbackend/platforms/windows/target/x86_64-pc-windows-msvc/release/rust.lib windows/          
@@ -320,7 +261,7 @@ jobs:
           cd ../../../..
 
       - name: Build (macos)
-        if: steps.check_asset.outputs.skip_build != 'true' && matrix.config.target == 'macos'
+        if: matrix.config.target == 'macos'
         run: |
           rustup target install x86_64-apple-darwin
           rustup target install aarch64-apple-darwin
@@ -338,7 +279,7 @@ jobs:
           cd ..
 
       - name: Sign APK (Android)
-        if: steps.check_asset.outputs.skip_build != 'true' && ( matrix.config.target == 'android-arm32' || matrix.config.target == 'android-arm64' || matrix.config.target == 'android-x86_64' )
+        if: ( matrix.config.target == 'android-arm32' || matrix.config.target == 'android-arm64' || matrix.config.target == 'android-x86_64' )
         env:
           KEY_FILE_BASE64: ${{ secrets.KEY_FILE_BASE64 }}
           KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
@@ -347,42 +288,37 @@ jobs:
           base64 -d key.jks.base64 > key.jks
           echo $KEY_PASSWORD | $ANDROID_HOME/build-tools/30.0.2/apksigner sign --ks key.jks build/app/outputs/flutter-apk/app-release.apk
 
-      - name: Upload Asset (All)
-        if: steps.check_asset.outputs.skip_build != 'true'
+      - name: Upload Asset (windows)
+        if: matrix.config.target == 'windows'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          cd ci
-          cargo run --bin upload-asset
+          $VERSION = (Get-Content -Path "ci/version.code.txt").Trim()
+          echo "Uploading asset ${{ github.event.repository.name }}-$VERSION-windows-x86_64.zip"
+          gh release upload $VERSION "build/windows.zip#${{ github.event.repository.name }}-$VERSION-windows-x86_64.zip" --clobber
 
-  community_notify:
-    name: community notify
-    runs-on: ubuntu-latest
-    needs:
-      - build_release_assets
-    env:
-      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
-      TG_CHAT_IDS: ${{ secrets.TG_CHAT_IDS }}
-      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
-      DISCORD_CHAT_IDS: ${{ secrets.DISCORD_CHAT_IDS }}
-    steps:
+      - name: Upload Asset (non-windows)
+        if: matrix.config.target != 'windows'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          export VERSION=$(cat ci/version.code.txt | xargs echo)
+          declare -A asset_dict
+          asset_dict["ios"]="${{ github.event.repository.name }}-$VERSION-nosign.ipa"
+          asset_dict["android-arm64"]="${{ github.event.repository.name }}-arm64-$VERSION.apk"
+          asset_dict["windows"]="${{ github.event.repository.name }}-$VERSION-windows-x86_64.zip"
+          asset_dict["linux"]="${{ github.event.repository.name }}-$VERSION.AppImage"
+          asset_dict["macos"]="${{ github.event.repository.name }}-$VERSION.dmg"
+          declare -A asset_path_dict
+          asset_path_dict["ios"]="build/nosign.ipa"
+          asset_path_dict["android-arm64"]="build/app/outputs/flutter-apk/app-release.apk"
+          asset_path_dict["windows"]="build/windows.zip"
+          asset_path_dict["linux"]="build/linux.AppImage"
+          asset_path_dict["macos"]="build/macos.dmg"
+          
+          asset_name = ${asset_dict[$(echo ${{ matrix.config.target }})]}
+          asset_path = ${asset_path_dict[$(echo ${{ matrix.config.target }})]}
+          
+          echo "Uploading asset $asset_name from $asset_path"
+          gh release upload $VERSION "$asset_path#$asset_name" --clobber
 
-      - name: Cargo cache
-        uses: actions/cache@v3
-        with:
-          path: |
-            ~/.cargo/bin/
-            ~/.cargo/registry/index/
-            ~/.cargo/registry/cache/
-            ~/.cargo/git/db/
-          key: ${{ runner.os }}-cargo-
-
-      - name: Install rust toolchain
-        uses: actions-rs/toolchain@v1
-        with:
-          toolchain: ${{ env.RUST_TOOLCHAIN }}
-
-      - name: Checkout
-        uses: actions/checkout@v3
-
-      - run: |
-          cd ci
-          cargo run --bin community-notify
